// Autogenerated by https://github.com/Mutagen-Modding/Mutagen.Bethesda.FormKeys

using Mutagen.Bethesda.Skyrim;
using Mutagen.Bethesda.Plugins;

namespace Mutagen.Bethesda.FormKeys.SkyrimSE;

public static partial class ThrowStuff
{
    public static partial class Explosion
    {
        private static FormLink<IExplosionGetter> Construct(uint id) => new FormLink<IExplosionGetter>(ModKey.MakeFormKey(id));
        public static FormLink<IExplosionGetter> _SOL_PoisonEXP => Construct(0x29);
        public static FormLink<IExplosionGetter> _SOL_PotionEXP => Construct(0x2a);
        public static FormLink<IExplosionGetter> _SOL_HeartEXP => Construct(0x35);
        public static FormLink<IExplosionGetter> _SOL_SilverEXP => Construct(0x36);
        public static FormLink<IExplosionGetter> _SOL_WhiteGlassEXP => Construct(0x3e);
        public static FormLink<IExplosionGetter> _SOL_SoulEXP => Construct(0x41);
        public static FormLink<IExplosionGetter> _SOL_KnockDownEXP => Construct(0x43);
        public static FormLink<IExplosionGetter> _SOL_WhiteDustEXP => Construct(0x44);
        public static FormLink<IExplosionGetter> _SOL_BlackDustEXP => Construct(0x47);
        public static FormLink<IExplosionGetter> _SOL_BloodEXP => Construct(0x37);
        public static FormLink<IExplosionGetter> _SOL_EmptyBottleEXP => Construct(0x39);
        public static FormLink<IExplosionGetter> _SOL_FrostBombEXP => Construct(0xb);
        public static FormLink<IExplosionGetter> _SOL_NoSoulEXP => Construct(0x49);
        public static FormLink<IExplosionGetter> _SOL_PoisonBombEXP => Construct(0xc);
        public static FormLink<IExplosionGetter> _SOL_ShockBombEXP => Construct(0xd);
        public static FormLink<IExplosionGetter> _SOL_SoupEXP => Construct(0x48);
        public static FormLink<IExplosionGetter> _SOL_ImpulseSm => Construct(0x1a);
        public static FormLink<IExplosionGetter> _SOL_Alcohol_LEXP => Construct(0x38308);
        public static FormLink<IExplosionGetter> _SOL_BlackDustSmallEXP => Construct(0x4b);
        public static FormLink<IExplosionGetter> _SOL_HolyEXP => Construct(0x38);
        public static FormLink<IExplosionGetter> _SOL_Potion_LEXP => Construct(0x3830b);
        public static FormLink<IExplosionGetter> _SOL_FirebombEXP => Construct(0xa);
        public static FormLink<IExplosionGetter> _SOL_Blood_LEXP => Construct(0x4250d);
        public static FormLink<IExplosionGetter> _SOL_WhiteDustSmallEXP => Construct(0x4a);
        public static FormLink<IExplosionGetter> _SOL_BlackDust_LEXP => Construct(0x38309);
        public static FormLink<IExplosionGetter> _SOL_FireExplosionSm => Construct(0x1b);
        public static FormLink<IExplosionGetter> _SOL_BlackDustSmall_LEXP => Construct(0x3830a);
        public static FormLink<IExplosionGetter> _SOL_Poison_LEXP => Construct(0x4760e);
        public static FormLink<IExplosionGetter> _SOL_CoinEXP => Construct(0x60b12);
        public static FormLink<IExplosionGetter> _SOL_OilEXP => Construct(0x1e);
        public static FormLink<IExplosionGetter> _SOL_AlcoholEXP => Construct(0x20);
    }
}
